[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
test_rng = "5fiZruYuczm75PhTWhkoug5xaZUPtLEmzqc2AWYyZDzM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/mert/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
